name: Release Build
on:
  push:
    tags:
      - *

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v2
      - run: go build -v .
      - run: |
          go get -u github.com/mitchellh/gox
          go get -u github.com/tcnksm/ghr
      - run: |
           gox -os="linux windows" -arch="amd64 arm" -output="dist/ayame_{{.OS}}_{{.Arch}}"
           gox -os="darwin" -arch="amd64" -output="dist/ayame_{{.OS}}_{{.Arch}}"
           cd dist/ && gzip *
      - env:
           GITHUB_TOKEN: ${{ secrets.token }}
           REPONAME: ${{ github.repository }}
           USERNAME: ${{ github.actor }}
           TAGNAME: ${{ github.ref }}
        run: ghr -t $GITHUB_TOKEN -u $USERNAME -r $REPONAME --replace $TAGNAME dist/
