name: Release Build
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: echo "::set-env name=TAG::${GITHUB_REF#refs/tags/}"
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'
      - uses: actions/checkout@v2
      - run: go build -v .
      - run: |
          go get -u github.com/mitchellh/gox
          go get -u github.com/tcnksm/ghr
      - run: |
           gox -os="linux" -arch="amd64 arm" -output="dist/ayame_{{.OS}}_{{.Arch}}"
           gox -os="darwin windows" -arch="amd64" -output="dist/ayame_{{.OS}}_{{.Arch}}"
           cd dist/ && gzip *
      - run: ghr -t "${{ github.token }}" -u "${{ github.actor }}" -r "ayame" --replace "${{ env.TAG }}" dist/
